# Module: NumPy Assignments

## Lesson: NumPy

In [2]:
import numpy as np 

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [3]:
arry = np.random.randint(1,21,size=(5,5))
arry[:,2] = 1
arry

array([[ 2,  2,  1,  1, 10],
       [16,  4,  1, 15,  3],
       [17, 18,  1,  5,  7],
       [ 2, 19,  1,  1,  9],
       [ 9,  7,  1,  4, 17]], dtype=int32)

In [4]:
arry = np.random.randint(1,17,size=(4,4))
np.fill_diagonal(arry, 0)
arry

array([[ 0,  6, 13, 15],
       [12,  0, 16,  8],
       [ 2, 11,  0,  9],
       [13,  4,  7,  0]], dtype=int32)

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [5]:
arry2 = np.random.randint(1,37,size=(6,6))
arry2[:]

array([[ 7, 17, 29, 28,  8, 24],
       [20, 12, 34, 27, 33, 11],
       [ 9, 10, 28, 18, 21, 35],
       [ 3, 25, 23, 35,  8,  6],
       [11,  3,  8, 34, 31,  7],
       [32, 18, 12, 12, 24, 29]], dtype=int32)

In [6]:
arry2[2:5,1:4]

array([[10, 28, 18],
       [25, 23, 35],
       [ 3,  8, 34]], dtype=int32)

In [7]:
# Create a 5x5 array with random integers between 0 and 100
arr3 = np.random.randint(0, 101, size=(5, 5))

print(arr3)


[[ 22  26  73  32  86]
 [  3   3  10  63  40]
 [ 77  67   0  69  58]
 [ 96  98  36  63 100]
 [ 60   7  53  11  43]]


In [8]:
#extracting the elements on the border of the array
border_elements = np.concatenate((arr3[0, :], arr3[-1, :], arr3[:, 0], arr3[:, -1]))
print("Border elements:", border_elements)

Border elements: [ 22  26  73  32  86  60   7  53  11  43  22   3  77  96  60  86  40  58
 100  43]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [9]:
arr1 = np.random.randint(1, 16, size=(3, 4))
arr2 = np.random.randint(1, 16, size=(3, 4))
print(f"Array 1:\n {arr1}")
print(f"Array 2:\n {arr2}")

Array 1:
 [[15  8 15 10]
 [12  2 14  8]
 [ 4  4  6 13]]
Array 2:
 [[ 4  3  5  9]
 [13 11  8 12]
 [ 4  5 11  9]]


In [10]:
addition = arr1 + arr2
print(f"Addition:\n {addition}")

subtraction = arr1 - arr2
print(f"Subtraction:\n {subtraction}")

multiplication = arr1 * arr2
print(f"Multiplication:\n {multiplication}")

division = arr1 / arr2
print(f"Division:\n {division}")



Addition:
 [[19 11 20 19]
 [25 13 22 20]
 [ 8  9 17 22]]
Subtraction:
 [[11  5 10  1]
 [-1 -9  6 -4]
 [ 0 -1 -5  4]]
Multiplication:
 [[ 60  24  75  90]
 [156  22 112  96]
 [ 16  20  66 117]]
Division:
 [[3.75       2.66666667 3.         1.11111111]
 [0.92307692 0.18181818 1.75       0.66666667]
 [1.         0.8        0.54545455 1.44444444]]


In [11]:
# row wise and column wise sum
arry = np.random.randint(1, 17, size=(4, 4))
arry

array([[15,  8,  4,  5],
       [13, 13,  3,  5],
       [10, 12,  1,  4],
       [ 2,  6,  4,  8]], dtype=int32)

In [12]:
print(f"Column wise sum: {arry.sum(axis=0)}") # column wise sum
print(f"Row wise sum:{arry.sum(axis=1)}") # row wise sum

Column wise sum: [40 39 12 22]
Row wise sum:[32 34 27 20]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [13]:
array = np.random.randint(1,21, size=(5, 5))
array

array([[18,  1,  7, 16, 15],
       [11,  9,  4, 13,  6],
       [17, 20, 19, 15,  5],
       [ 6, 17,  3, 14,  7],
       [ 5, 20,  1, 15,  7]], dtype=int32)

In [14]:
mean = array.mean()
print(f"Mean: {mean}") # mean of all elements
median = np.median(array)
print(f"Median: {median}") # median of all elements
std_dev = array.std()
print(f"Standard Deviation: {std_dev}") # standard deviation of all elements
variance = array.var()
print(f"Variance: {variance}") # variance of all elements

Mean: 10.84
Median: 11.0
Standard Deviation: 6.064189970639112
Variance: 36.77439999999999


In [15]:
ary = np.random.randint(1,10, size=(3, 3))
ary

array([[9, 3, 9],
       [7, 5, 5],
       [7, 6, 9]], dtype=int32)

In [16]:
z= ary.mean()
x = ary.std()
print(f"Mean: {z}") # mean of all elements
print(f"Standard Deviation: {x}") # standard deviation of all elements

Mean: 6.666666666666667
Standard Deviation: 2.0


In [17]:
standardized = (ary - ary.mean()) / ary.std()
print(f"Standardized array:\n {standardized}") # standardize the array

Standardized array:
 [[ 1.16666667 -1.83333333  1.16666667]
 [ 0.16666667 -0.83333333 -0.83333333]
 [ 0.16666667 -0.33333333  1.16666667]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [18]:
# Create a NumPy array of shape (3, 3) filled with random integers
array = np.random.randint(1, 11, size=(3, 3))
row_array = np.random.randint(1, 11, size=(3,))
print("Original array:")
print(array)
print("1D array:")
print(row_array)

# Add the 1D array to each row of the 2D array using broadcasting
result = array - row_array
print("Resulting array:")
print(result)

Original array:
[[ 8  4  3]
 [ 2 10  4]
 [ 2 10  5]]
1D array:
[ 9  2 10]
Resulting array:
[[-1  2 -7]
 [-7  8 -6]
 [-7  8 -5]]


In [19]:
# Create a NumPy array of shape (4, 4) filled with random integers
array2 = np.random.randint(1, 11, size=(4, 4))
col_array = np.random.randint(1, 11, size=(4,))
print("Original array:")
print(array2)
print("1D array:")
print(col_array)

# Subtract the 1D array to each row of the 2D array using broadcasting
result = array2 - col_array
print("Resulting array:")
print(result)

Original array:
[[ 5  6  6  3]
 [ 3  1  2  1]
 [ 9 10  2  2]
 [ 6 10  9  4]]
1D array:
[ 1 10  9  2]
Resulting array:
[[ 4 -4 -3  1]
 [ 2 -9 -7 -1]
 [ 8  0 -7  0]
 [ 5  0  0  2]]



### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [20]:
arry = np.random.randint(1, 21, size=(3, 3))
print(f"Orignial Array:\n {arry}")
arry_determinant = np.linalg.det(arry)
print(f"Determinant of the array: {arry_determinant}") # determinant of the array
arry_inverse = np.linalg.inv(arry)
print(f"Inverse of the array:\n {arry_inverse}") # inverse of the array
arry_eigenvalues, arry_eigenvectors = np.linalg.eig(arry)
print(f"Eigenvalues of the array: {arry_eigenvalues}") # eigenvalues of the array

Orignial Array:
 [[20  7  8]
 [10  1  5]
 [ 3  1 20]]
Determinant of the array: -939.0
Inverse of the array:
 [[-0.01597444  0.14057508 -0.02875399]
 [ 0.1970181  -0.40042599  0.02129925]
 [-0.00745474 -0.00106496  0.05324814]]
Eigenvalues of the array: [-2.16201556 27.18662529 15.97539027]


In [21]:
a1 = np.random.randint(1, 21, size=(2,3))
a2 = np.random.randint(1, 21, size=(3,2))
print(f"Array 1:\n {a1}")
print(f"Array 2:\n {a2}")
matrix_multiplication = np.dot(a1, a2)
print(f"Matrix Multiplication:\n {matrix_multiplication}") # matrix multiplication

Array 1:
 [[ 7 10  5]
 [ 4  2 16]]
Array 2:
 [[18  5]
 [20 19]
 [20 10]]
Matrix Multiplication:
 [[426 275]
 [432 218]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [28]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reshape_arr = arr.reshape(1, 9)
reshpape_arr2 = arr.reshape(9, 1)
print(f"Original Array:\n {arr}")
print(f"Reshaped Array:\n {reshape_arr}") # reshaped array to 1x9
print(f"Reshaped Array:\n {reshpape_arr2}") # reshaped array to 9x1

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped Array:
 [[1 2 3 4 5 6 7 8 9]]
Reshaped Array:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [ ]:
array = np.random.randint(1, 21, size=(5, 5))
print(f"Original Array:\n {array}")
flatten_array = array.flatten()
print(f"Flattened Array:\n {flatten_array}") # flatten the array
flatten_reshape = flatten_array.reshape(5, 5)
print(f"Reshaped Array:\n {flatten_reshape}") # reshaped array to 5x5

Original Array:
 [[11  2 16  5  1]
 [ 9 12 10 18  4]
 [ 3 13  9 16 20]
 [20  8  8 15  1]
 [ 6 10  6  3 11]]
Flattened Array:
 [11  2 16  5  1  9 12 10 18  4  3 13  9 16 20 20  8  8 15  1  6 10  6  3
 11]
Reshaped Array:
 [[11  2 16  5  1]
 [ 9 12 10 18  4]
 [ 3 13  9 16 20]
 [20  8  8 15  1]
 [ 6 10  6  3 11]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [39]:
s1 = np.random.randint(1,21, size=(5, 5))
print(f"Array:\n {s1}")
# Get corner elements using fancy indexing
corner_indices = [[0, 0], [0, -1], [-1, 0], [-1, -1]]  # [top-left, top-right, bottom-left, bottom-right]
rows, cols = zip(*corner_indices)
corners = s1[list(rows), list(cols)]

print("Corner elements:", corners)

Array:
 [[15 19  8  2 12]
 [11  6 15  2 15]
 [17 11 13 16 20]
 [11 20  5  4 16]
 [ 7 12 13  6 20]]
Corner elements: [15 12  7 20]


In [47]:
s2 = np.random.randint(1, 16, size=(4, 4))
print("Original array:\n", s2)

# Create a copy if you don't want to change the original
s2_masked = s2.copy()

# Apply mask
mask = s2_masked > 10
s2_masked[mask] = 10

print("Masked array:\n", s2_masked)


Original array:
 [[11  6  3  5]
 [12 15  4  5]
 [ 5  3 13  2]
 [ 1  4  6  8]]
Masked array:
 [[10  6  3  5]
 [10 10  4  5]
 [ 5  3 10  2]
 [ 1  4  6  8]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [62]:
# Structured array
dtype = [('name', 'U10'), ('age', 'int'), ('weight', 'float')]
data = np.array([
    ('Alice', 25, 55.5),
    ('Bob', 30, 72),
    ('Charlie', 22, 68.3)
], dtype=dtype)

# Sort by 'age'
sorted_data = np.sort(data, order='age')

print(sorted_data)


[('Charlie', 22, 68.3) ('Alice', 25, 55.5) ('Bob', 30, 72. )]


In [63]:
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

# Compute the Euclidean distance between each pair of points
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [ ]:
from numpy import ma as ma
# import numpy.ma as ma
# Create a masked array of shape (4, 4) with random integers
array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Compute the sum of the unmasked elements
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
[[ 6  7 17  4]
 [15 16  1  7]
 [17 13 16  9]
 [15 20  6 19]]
Masked array:
[[6 7 -- 4]
 [-- -- 1 7]
 [-- -- -- 9]
 [-- -- 6 --]]
Sum of unmasked elements: 40


In [69]:
array = np.random.randint(1,21, size=(3, 3) )
masked_array = ma.masked_array(array,mask=np.eye(3, dtype=bool))
print(f"Original Array:\n {array}")
print(f"Masked Array:\n {masked_array}")

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)


Original Array:
 [[13  7 17]
 [12  7 20]
 [18  3  3]]
Masked Array:
 [[-- 7 17]
 [12 -- 20]
 [18 3 --]]
Modified masked array:
[[12  7 17]
 [12 12 20]
 [18  3 12]]
